### ISSUE TITLE
Allow root workflows to emit multiple outputs to their activities/fragments

### ISSUE THREAD

**Issue by bnvinay92** [square/workflow-kotlin#109]
A multi-activity application may require the root fragment/activity to handle multiple navigation requests throughout the session of a workflow.

**Comment by grandstaish** [comment]
I'm also looking at migrating one of my existing apps to use Workflow and am unsure of what to do about Activity navigation. It seems intuitive to me to use Workflow outputs as the trigger for a navigation event, e.g. [like this](https://github.com/grandstaish/workflow-legacy-app-migration-example/blob/master/app/src/main/java/nz/bradcampbell/legacyappwithworkflows/main/MainActivity.kt). But of course this code is broken because once a result is emitted, the Workflow is shutdown. 

Do you have any suggestions for how I could migrate my app differently?
