### ISSUE TITLE
Incorrect layout when update() is not called on all WorkflowViewStubs in a LinearLayout

### ISSUE THREAD

**Issue by bnvinay92** [square/workflow-kotlin#170]
Reproduced here: https://github.com/square/workflow-kotlin/compare/main...careem:reproduce-workflow-viewstub-issue

Layout:

```
<LinearLayout orientation="vertical">
  <WorkflowViewStub
    background="red"
    height="0dp"
    weight="1" />

  <TextView
    background="orange"
    height="wrap_content" />

  <com.squareup.workflow1.ui.WorkflowViewStub
    background="green"
    height="wrap_content" />
</LinearLayout>

```
Rendered as:

![Screenshot_1597680505](https://user-images.githubusercontent.com/22435681/90418355-13e2d280-e0c6-11ea-8478-5991ce6d032c.png)

If the red viewStub is inflated but the green one is not, then the red viewstub has zero height and the green view stub height matches parent. Inflating both results in a correct rendering.
More here: https://workflow-community.slack.com/archives/CHTFPR277/p1597683241264200?thread_ts=1597672694.261300&cid=CHTFPR277

**Comment by rjrjr** [comment]
Discussion in #177 distills down to: add a `updateSetsVisibility` val / xml attribute, default to `true`.

**Comment by rjrjr** [comment]
@bnvinay92 @zach-klippenstein Seems like we'd have the same issue with `setBackground`, no?

**Comment by rjrjr** [comment]
Actually I guess that's not necessary, since `background` is nullable and only clobbers the background if it is set to something. The lack of parallelism between the two attributes is kind of uncomfortable, but then the value types and the use cases are pretty distinct too. Having the child be in charge of its own background is a pretty different concern than having it be in charge of its own visibility, and I think expectations differ.
