### ISSUE TITLE
TextChangedListenerWatcher is causing weird text in EditText

### ISSUE THREAD

**Issue by tir38** [square/workflow-kotlin#384]
Typing text is weirdly duplicated. This is visible in tutorial # 3:

![2021-03-18 18 44 09](https://user-images.githubusercontent.com/1980553/112022310-91f9d280-8b08-11eb-9da5-ad394c31639a.gif)

I'm pretty sure the bug is in `TextChangedListenerWatcher`, not the usage of `TextChangedListenerWatcher` in the tutorial. It is definitely on the "listener" side, not the "update" text side of the process i.e. the error is already present before calling `EditText.updateText`.

**Comment by NickvanDyke** [comment]
I have experienced this too, but only when using EditTexts in recyclerviews (specifically with Groupie, in case that matters). Googling "android edittext duplicating content" brings up some maybe relevant stuff. Changing the editText's inputType to text visible password fixed it for me, although not ideal since then you lose other functionality, such as autocomplete, and afaict it's impossible to also make the edittext multi-line while using that.

**Comment by rjrjr** [comment]
See also #414

**Comment by NickvanDyke** [comment]
Also it doesn't occur if I use my computer's keyboard to type, but does when I use the emulator's IME, I believe GBoard. So maybe some weird interaction with the IMEs autocorrect, since that's disabled with textVisiblePassword. textNoSuggestions should also disable and fix it, but GBoard doesn't seem to respect that. I have seen buggy autocorrect and InputFilter implementations mentioned as causes of the duplicating when googling.

**Comment by rjrjr** [comment]
Internally we've been working on a much less ambitious approach to all this. Hoping to validate and open source it soon.

**Comment by rjrjr** [comment]
Fixed by `TextController`.
