### ISSUE TITLE
Root runWorkflowLoop has inconsistent output behavior compared to its WorkflowNode children 

### ISSUE THREAD

**Issue by Blisse** [square/workflow-kotlin#54]
In `RealWorkflowLoop#runWorkflowLoop`, the order of operations after an output for the root workflow's runWorkflowLoop is:

1. `output = select { .. }`
2. `doRender`
3. `output?.let { onOutput }`

However, child workflows have their outputs immediately executed when the WorkflowAction is run.

* From `WorkflowNode#tick` we call `WorkflowNode#applyAction`, but notice that we call `output?.let(emitOutputToParent)` immediately.

This difference in behavior manifests in the root workflow performing an extra render pass before the root workflow runner can receive an output and potentially end the workflow. 

This extra render pass can cause a crash if the workflow does not expect to have render called after emitting an output (because the presumption is that the output stop the workflow from running).

---

To work around this, I can wrap my root workflow `R` in another workflow `P` that has 2 states: Running and CancelledAfterOutput. Initially, `P` will be in the Running state, and call renderChild on `R`. But after 1 output from `R`, `P` transitions to the CancelledAfterOutput state, which doesn't call renderChild on `R`. This "fixes" the errant extra render pass.

**Comment by zach-klippenstein** [comment]
> Currently the main use for listening to outputs is cancelling the workflow/navigating away, so it's unlikely anyone is really interested in workflow state in those cases.

This turns out to be wrong in a very specific way. A very common pattern we use internally of using outputs to navigate "away" is to navigate "to" a legacy part of the app, where the workflow runtime is shutdown but the last snapshot is kept in the backstack, so if the user navigates back past the legacy screens, the workflow runtime is restarted from the last snapshot. If outputs are emitted before snapshots, that snapshot will be stale.

This is exactly what I was referring to by “consistency” in [this comment](https://github.com/square/workflow-kotlin/issues/54#issuecomment-621324326), although I had not thought of this particular case. When the output is emitted, the runtime is in an “inconsistent” state – the action has only been “half” applied. Technically, when the rendering/snapshot is emitted first, the action has also only been “half” applied. However, renderings/snapshots and outputs are different types of streams. Rendering/snapshot is “state”, and output is an “event”. The significance of event streams is the actual emission of the event, and the timing matters. State is not time-sensitive, in a sense – there is always a “current” state, and the state may be different at two different instants but all that matters is the value of the state “now”. Another way to think about this is that event emissions "delineate" time, state changes occur “between” instants in time – between any two points in time, the state may have changed or not, but all that matters at any given instant is what the state is at that time, regardless of whether it changed from the previous instant. For this to work correctly with workflows, renderings/snapshots need to be emitted before events.
