### ISSUE TITLE
TextController doesn't allow me to insert my own TextWatcher

### ISSUE THREAD

**Issue by csydserff** [square/workflow-kotlin#882]
I have something else that needs to be inserted into the chain of updates.

**Comment by rjrjr** [comment]
Can you go into more detail about your use case? You should be able to have multiple TextWatchers attached to a TextView, no?

**Comment by steve-the-edwards** [comment]
Hey @rjrjr I worked on this with @csydserff in a pairing and suggested to create this issue. They ended up solving it another way I believe and we could likely close this issue. The general problem is that we need the controller to be driven by the outcome of another TextWatcher.

E.g., - edit text is edited - then a TextWatcher picks that up and scrubs it (causing a change again) - then the TextWatcher which drives the TextController gets pinged.

Otherwise they race.
